### PR TITLE
[HORNETQ-1482] Add WARN log when setting connection-ttl OR connection…

### PR DESCRIPTION
**Pull request by ryanemerson**
…-ttl-override equal to check-period

https://bugzilla.redhat.com/show_bug.cgi?id=1175722

### CODE REVIEW

**Comment by mtaylor** [comment]
ok to test

**Comment by clebertsuconic** [comment]
retest this please

**Comment by clebertsuconic** [comment]
Merged!

**Comment by clebertsuconic** [comment]
cherry-picked into 2.3.25.x

**Pull request closed without merging**
