### PR TITLE
NO-JIRA Improve and Fix tests

### PR DESCRIPTION
**Pull request by gaohoward**
- Increase some timeouts
- Improve wait
- Fix some incorrect tests
- Add more logging in tests

### CODE REVIEW

**Comment by gaohoward** [comment]
@clebertsuconic Hi I've done some test cleanup, can you review? thx.

**Comment by gaohoward** [comment]
@clebertsuconic Can I merge this myself? It's for improving tests.

**Comment by clebertsuconic** [comment]
@gaohoward you have to make sure these make into artemis.

**Comment by clebertsuconic** [comment]
@gaohoward  please.. don't use merge commits, they make things messy.

Rebase and merge please.

**Pull request merged**
