### PR TITLE
Changed log level to debug.

### PR DESCRIPTION
**Pull request by TomRoss**
This can be very annoying if two different version of HornetQ are used.

### CODE REVIEW

**Comment by TomRoss** [comment]
Please merge this change.

**Comment by jbertram** [comment]
ok to test

**Comment by jbertram** [comment]
@TomRoss, 

Just to be clear, the only way a client could avoid this message when connecting to a server is by updating its jars to get this change.  In most cases users will not want to update their clients and if they did they could simply move to the latest version which would not produce this message in the first place.

**Comment by clebertsuconic** [comment]
+1

**Pull request merged**
