### PR TITLE
Throw runtime exception with problem description when creating durable topic consumer with null subscription name and non-durable topic consumer with not-null subscription name.

### PR DESCRIPTION
**Pull request by tychinasg**

### CODE REVIEW

**Comment by mtaylor** [comment]
OK to test

**Comment by jbertram** [comment]
ok to test

**Comment by tychinasg** [comment]
Fixed.

**Comment by jbertram** [comment]
Can you squash the two commits together?  No need to have 2 separate commits here.

**Comment by jbertram** [comment]
FYI - Typically commits are squashed together using this command:

`git rebase -i upstream/master`

**Comment by tychinasg** [comment]
Got it. Sorry for this issue. Should we somehow revert it or leave AS IS?

**Comment by clebertsuconic** [comment]
Probably the best would be to use jboss-logging to i18n the text

**Comment by jbertram** [comment]
Rebasing and squashing multiple commits into one is a simple and common process.  It's poor form to have multiple commits for a single change.

**Comment by clebertsuconic** [comment]
I wouldn't accept this change anyways.. it needs to be through i18n

**Comment by jbertram** [comment]
To your point, @clebertsuconic, there's a handful of exceptions in there already that don't use JBoss Logging so I didn't see much harm in one more.

**Comment by clebertsuconic** [comment]
@jbertram  ah.. good point then

**Comment by jbertram** [comment]
There are now 4 commits associated with this PR.  Please rebase and squash everything down to a single commit.

**Comment by clebertsuconic** [comment]
I'm adding a new PR rebased replacing this
@tychinasg you should read some doc on git... you should rebase your commits before PR.

**Pull request closed without merging**
