### PR TITLE
Make NetworkHealthTestCheckTest more stable.

### PR DESCRIPTION
**Pull request by dudaerich**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@dudaerich did you make this change in artemis as well?

**Comment by dudaerich** [comment]
No, I totally forgot on it. I'll look at it in Artemis and send a PR.

**Comment by clebertsuconic** [comment]
Merged it with a cherry-pick...

@dudaerich I'm not sure the changes apply in artemis.. but if you could look please?

**Comment by dudaerich** [comment]
@clebertsuconic I took a look. You are right, changes doesn't apply to Artemis. I also tried to run the network health check tests in Artemis and they are stable.

**Pull request closed without merging**
