### PR TITLE
[BZ-1339881] HornetQ still logs truststore and keystore passwords in …

### PR DESCRIPTION
**Pull request by msmerek**
…plain text

Merged upstream PR: https://github.com/apache/activemq-artemis/pull/557
Upstream JIRA: https://issues.apache.org/jira/browse/ARTEMIS-551
EAP 7 JIRA: https://issues.jboss.org/browse/JBEAP-4852
EAP 6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1339881

Question: does this also need to go into 2.4.x? Thank you very much

### CODE REVIEW

**Comment by gaohoward** [comment]
ok to test

**Comment by msmerek** [comment]
retest this please

**Comment by msmerek** [comment]
The failures do not seem to be related.

**Comment by clebertsuconic** [comment]
@msmerek  did you check Artemis?

**Comment by clebertsuconic** [comment]
@msmerek never mind, @jbertram  told me this is fixed on artemis

**Comment by clebertsuconic** [comment]
duh! https://github.com/apache/activemq-artemis/pull/557

**Pull request merged**
