### PR TITLE
[GSS](6.4.z) HornetQ Client trying to use wrong keystore

### PR DESCRIPTION
**Pull request by treblereel**
[HORNETQ-1237] Add a HornetQ-specific system property for setting the keystore and truststore path on the client
BZ 6.4.x https://bugzilla.redhat.com/show_bug.cgi?id=1288578
pr to 2.3.x https://github.com/hornetq/hornetq/pull/2066
no upstream required

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Is this a cherry-pick, can you do cherry-pick -x, or amend with the ID?

**Comment by clebertsuconic** [comment]
ok to test

**Comment by treblereel** [comment]
cherry-pick failed, so i did it by my self

**Comment by clebertsuconic** [comment]
The proper way should be this sent into 2.3.x, and then cherry-pick -x into 2.3.25.x

Is this sent into 2.3.x as well?

**Comment by treblereel** [comment]
i am not sure,but if we need it, i could do
ps: thanks for advice

**Comment by clebertsuconic** [comment]
I cherry-picked it manually from 2.3.x, closing this

**Pull request closed without merging**
