### PR TITLE
Fix for totalIterator() fails to retrieve scheduled messages - HORNETQ-1458

### PR DESCRIPTION
**Pull request by balint133**

### CODE REVIEW

**Comment by gaohoward** [comment]
ok to test

**Comment by clebertsuconic** [comment]
not a bug!

Any reason why you think this is a bug?

**Comment by clebertsuconic** [comment]
closing as this is not a bug!!!

**Comment by balint133** [comment]
Hmm yes your comment is right they are not supposed to be delivered, sorry. 

The reason I've opened this (as you can see in my forum discussion) because If I call QueueControl#countMessages() with a filter it uses this iterator and I am not able to retrieve scheduled messages with that filter. However calling it without a filter calls Queue#getMessageCount which gives back the number of all messages (including scheduled ones).

This behavior is not documented and I guess I should be able to filter scheduled messages as well.

**Pull request closed without merging**
