### PR TITLE
[HORNETQ-1482] Add WARN log when setting connection-ttl OR connection…

### PR DESCRIPTION
**Pull request by ryanemerson**
…-ttl-override equal to check-period

https://bugzilla.redhat.com/show_bug.cgi?id=1175722

### CODE REVIEW

**Comment by jbertram** [comment]
ok to test

**Comment by jbertram** [comment]
BTW, this should be fixed upstream on https://github.com/apache/activemq-artemis to avoid regressions when upgrading.

**Comment by ryanemerson** [comment]
Upstream PR submitted: https://github.com/apache/activemq-artemis/pull/56

**Comment by jbertram** [comment]
Thanks, @ryanemerson.

**Comment by jbertram** [comment]
please retest

**Pull request merged**
