### PR TITLE
HORNETQ-626: Allows udp.broadcast.group.ttl System property to be set…

### PR DESCRIPTION
**Pull request by majikthys**
… to specify udp broadcast ttl, which is necessary to transmit beyond immediate network

### CODE REVIEW

**Comment by clebertsuconic** [comment]
can you squash the checkstyle file?

Also.. can you send the same into artemis? otherwise this will be lost on EAP7 and future versions of Artemis

**Comment by clebertsuconic** [comment]
@majikthys  can you rebase / squash the check style commit as the previous one?

**Comment by clebertsuconic** [comment]
hornetq is strictly in maintenance mode... have you checked how Artemis does this? it might be worth to check it there... maybe adjust it there.

Although I don't like the idea of system properties as well.

**Comment by siwanas** [comment]
Sivanus123@hotmail.com

**Comment by siwanas** [comment]
sivanus123@hotmail.com

10439

**Comment by majikthys** [comment]
stale

**Pull request closed without merging**
